# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64c1b0c118f651bcc3b6dd2b7afcea61f1826272b522469b234960ab7e31bf71507d5ced447729fe46b5480a359c3ae80a0e993e574f66625fde238d9c050a0e

test:
  secret_key_base: 2da1d3980e3640433b2e6fac7be2f38a86bfd1ab1c83e4dbea7477ba3af2e2172d971492ceb927ca14d14272529c7c003085adbba302d9d61efa4126c8963d44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
